Repository Travalue/Travalue-Server, pull requests merged in 2023-04, with the labels that each got.

#23 [Feat] 소셜 로그인 (KAKAO) API 구현
  build.gradle
  src/main/java/com/deploy/Travalue/common/util/model/EnumModel.java
  src/main/java/com/deploy/Travalue/common/util/model/EnumValue.java
  src/main/java/com/deploy/Travalue/config/WebConfig.java
  src/main/java/com/deploy/Travalue/config/interceptor/Auth.java
  src/main/java/com/deploy/Travalue/config/interceptor/AuthInterceptor.java
  src/main/java/com/deploy/Travalue/config/interceptor/LoginCheckHandler.java
  src/main/java/com/deploy/Travalue/config/jwt/JwtService.java
  src/main/java/com/deploy/Travalue/config/resolver/UserId.java
  src/main/java/com/deploy/Travalue/config/resolver/UserIdResolver.java
  src/main/java/com/deploy/Travalue/config/swagger/AuthorizationSwaggerConfig.java
  src/main/java/com/deploy/Travalue/config/swagger/SwaggerConfig.java
  src/main/java/com/deploy/Travalue/external/client/kakao/KaKaoApiClient.java
  src/main/java/com/deploy/Travalue/external/client/kakao/KaKaoAuthClient.java
  src/main/java/com/deploy/Travalue/external/client/kakao/response/KaKaoProfileResponse.java
  src/main/java/com/deploy/Travalue/external/client/kakao/response/KakaoTokenResponse.java
  src/main/java/com/deploy/Travalue/external/config/FeignClientConfig.java
  src/main/java/com/deploy/Travalue/user/controller/AuthController.java
  src/main/java/com/deploy/Travalue/user/controller/UserController.java
  src/main/java/com/deploy/Travalue/user/domain/SocialInformation.java
  src/main/java/com/deploy/Travalue/user/domain/User.java
  src/main/java/com/deploy/Travalue/user/domain/UserSocialType.java
  src/main/java/com/deploy/Travalue/user/dto/CreateUserDto.java
  src/main/java/com/deploy/Travalue/user/dto/request/LoginRequest.java
  src/main/java/com/deploy/Travalue/user/dto/response/LoginResponse.java
  src/main/java/com/deploy/Travalue/user/infrastructure/UserRepository.java
  src/main/java/com/deploy/Travalue/user/service/AuthService.java
  src/main/java/com/deploy/Travalue/user/service/AuthServiceProvider.java
  src/main/java/com/deploy/Travalue/user/service/KaKaoAuthService.java
  src/main/java/com/deploy/Travalue/user/service/UserService.java
Labels: 🧡 태윤, 🎃 Feat

#17 [Feat] Trailer 전체 조회 API
  src/main/java/com/deploy/Travalue/exception/SuccessCode.java
  src/main/java/com/deploy/Travalue/travel/controller/TravelController.java
  src/main/java/com/deploy/Travalue/travel/infrastructure/TravelRepository.java
  src/main/java/com/deploy/Travalue/travel/service/TravelService.java
  src/main/java/com/deploy/Travalue/travel/service/dto/response/TrailersResponseDto.java
Labels: 💚 서현, 🎃 Feat

#33 [feat]: user category 생성 API
  build.gradle
  src/main/java/com/deploy/Travalue/common/advice/ControllerExceptionAdvice.java
  src/main/java/com/deploy/Travalue/common/dto/ApiResponse.java
  src/main/java/com/deploy/Travalue/exception/ErrorCode.java
  src/main/java/com/deploy/Travalue/exception/StatusCode.java
  src/main/java/com/deploy/Travalue/exception/SuccessCode.java
  src/main/java/com/deploy/Travalue/exception/model/TravalueException.java
  src/main/java/com/deploy/Travalue/external/client/aws/S3Service.java
  src/main/java/com/deploy/Travalue/travel/controller/CategoryController.java
  src/main/java/com/deploy/Travalue/travel/controller/dto/request/CategoryRequestDto.java
  src/main/java/com/deploy/Travalue/travel/domain/Category.java
  src/main/java/com/deploy/Travalue/travel/infrastructure/CategoryRepository.java
  src/main/java/com/deploy/Travalue/travel/service/CategoryService.java
Labels: 🤍 승헌, 🎃 Feat

#35 [update]: category 생성 API 예외처리
  src/main/java/com/deploy/Travalue/common/advice/ControllerExceptionAdvice.java
  src/main/java/com/deploy/Travalue/config/resolver/UserIdResolver.java
  src/main/java/com/deploy/Travalue/exception/ErrorCode.java
  src/main/java/com/deploy/Travalue/travel/controller/dto/request/CategoryRequestDto.java
Labels: 🤍 승헌, 🎃 Feat

#37 Feat/#30 get travellers api
  src/main/java/com/deploy/Travalue/exception/SuccessCode.java
  src/main/java/com/deploy/Travalue/travel/controller/TravelController.java
  src/main/java/com/deploy/Travalue/travel/domain/Category.java
  src/main/java/com/deploy/Travalue/travel/domain/Travel.java
  src/main/java/com/deploy/Travalue/travel/infrastructure/TravelRepository.java
  src/main/java/com/deploy/Travalue/travel/service/TravelService.java
  src/main/java/com/deploy/Travalue/travel/service/dto/response/TravellersResponseDto.java
Labels: 💚 서현, 🎃 Feat
