Repository Travalue/Travalue-Server, pull requests merged in 2023-05, with the labels that each got.

#40 [feat] 카테고리 생성 API 에러 처리
  .gitignore
  src/main/java/com/deploy/Travalue/common/advice/ControllerExceptionAdvice.java
  src/main/java/com/deploy/Travalue/travel/controller/CategoryController.java
  src/main/java/com/deploy/Travalue/travel/controller/dto/request/CategoryRequestDto.java
Labels: 🤍 승헌, 🛠 Refactoring

#44 Feat: Traveller 상세조회 API
  src/main/java/com/deploy/Travalue/exception/SuccessCode.java
  src/main/java/com/deploy/Travalue/travel/controller/TravelController.java
  src/main/java/com/deploy/Travalue/travel/domain/Travel.java
  src/main/java/com/deploy/Travalue/travel/domain/TravelContent.java
  src/main/java/com/deploy/Travalue/travel/domain/TravelInformation.java
  src/main/java/com/deploy/Travalue/travel/domain/TravelPin.java
  src/main/java/com/deploy/Travalue/travel/infrastructure/TravelContentRepository.java
  src/main/java/com/deploy/Travalue/travel/infrastructure/TravelPinRepository.java
  src/main/java/com/deploy/Travalue/travel/service/TravelService.java
  src/main/java/com/deploy/Travalue/travel/service/dto/response/TravelContentsDto.java
  src/main/java/com/deploy/Travalue/travel/service/dto/response/TravelResponseDto.java
  src/main/java/com/deploy/Travalue/travel/service/dto/response/TravelScheduleDto.java
  src/main/java/com/deploy/Travalue/travel/service/dto/response/TravelWriterDto.java
  src/main/java/com/deploy/Travalue/travel/service/dto/response/TravellersResponseDto.java
Labels: 💚 서현, 🎃 Feat

#45 [feat] 나의 여행지 생성 API 수정
  src/main/java/com/deploy/Travalue/user/controller/myTrip/MyTripController.java
  src/main/java/com/deploy/Travalue/user/service/myTrip/MyTripService.java
Labels: 🤍 승헌, 🎃 Feat

#47 [feat] : 마이 페이지 조회 API 구현 / QueryDSL Config
  build.gradle
  src/main/java/com/deploy/Travalue/config/querydsl/QuerydslConfig.java
  src/main/java/com/deploy/Travalue/exception/SuccessCode.java
  src/main/java/com/deploy/Travalue/travel/domain/likeTavel/LikeTravel.java
  src/main/java/com/deploy/Travalue/travel/infrastructure/LikeTravelRepository.java
  src/main/java/com/deploy/Travalue/travel/infrastructure/TravelCustomRepository.java
  src/main/java/com/deploy/Travalue/travel/infrastructure/TravelCustomRepositoryImpl.java
  src/main/java/com/deploy/Travalue/travel/infrastructure/TravelRepository.java
  src/main/java/com/deploy/Travalue/user/controller/AuthController.java
  src/main/java/com/deploy/Travalue/user/controller/UserController.java
  src/main/java/com/deploy/Travalue/user/controller/dto/MyPageResponseDto.java
  src/main/java/com/deploy/Travalue/user/controller/dto/MyPageUserDto.java
  src/main/java/com/deploy/Travalue/user/controller/dto/SharedTravelDto.java
  src/main/java/com/deploy/Travalue/user/domain/User.java
  src/main/java/com/deploy/Travalue/user/service/UserService.java
Labels: 🧡 태윤, 🎃 Feat

#48 [feat] : 유저 차단 / 차단 해제
  src/main/java/com/deploy/Travalue/exception/SuccessCode.java
  src/main/java/com/deploy/Travalue/user/controller/UserController.java
  src/main/java/com/deploy/Travalue/user/controller/dto/UserBlockRequestDto.java
  src/main/java/com/deploy/Travalue/user/domain/block/BlockUser.java
  src/main/java/com/deploy/Travalue/user/infrastructure/block/BlockUserRepository.java
  src/main/java/com/deploy/Travalue/user/service/UserService.java
Labels: 🧡 태윤, 🎃 Feat

#49 Feat: 트레블 삭제 API
  src/main/java/com/deploy/Travalue/exception/SuccessCode.java
  src/main/java/com/deploy/Travalue/travel/controller/TravelController.java
  src/main/java/com/deploy/Travalue/travel/domain/Travel.java
  src/main/java/com/deploy/Travalue/travel/service/TravelService.java
Labels: 💚 서현, 🎃 Feat

#52 Feat: Traveller 검색 API 구현
  src/main/java/com/deploy/Travalue/exception/SuccessCode.java
  src/main/java/com/deploy/Travalue/travel/controller/TravelController.java
  src/main/java/com/deploy/Travalue/travel/infrastructure/TravelRepository.java
  src/main/java/com/deploy/Travalue/travel/service/TravelService.java
Labels: 💚 서현, 🎃 Feat

#54 Feat: 지금 핫한 Traveller 조회 API
  src/main/java/com/deploy/Travalue/exception/SuccessCode.java
  src/main/java/com/deploy/Travalue/travel/controller/TravelController.java
  src/main/java/com/deploy/Travalue/travel/infrastructure/TravelRepository.java
  src/main/java/com/deploy/Travalue/travel/service/TravelService.java
  src/main/java/com/deploy/Travalue/travel/service/dto/response/HotTravellersResponseDto.java
Labels: 💚 서현, 🎃 Feat

#56 Fix: Traveller 상세조회 API 수정
  src/main/java/com/deploy/Travalue/travel/controller/TravelController.java
  src/main/java/com/deploy/Travalue/travel/infrastructure/LikeTravelRepository.java
  src/main/java/com/deploy/Travalue/travel/service/TravelService.java
  src/main/java/com/deploy/Travalue/travel/service/dto/response/TravelResponseDto.java
  src/main/java/com/deploy/Travalue/travel/service/dto/response/TravelStatisticsDto.java
  src/main/java/com/deploy/Travalue/travel/service/dto/response/TravelWriterDto.java
Labels: 💚 서현, 🎃 Feat, 🛠 Refactoring

#57 Feat/#28 travel
  src/main/java/com/deploy/Travalue/common/advice/ControllerExceptionAdvice.java
  src/main/java/com/deploy/Travalue/exception/ErrorCode.java
  src/main/java/com/deploy/Travalue/exception/SuccessCode.java
  src/main/java/com/deploy/Travalue/travel/controller/TravelController.java
  src/main/java/com/deploy/Travalue/travel/controller/dto/request/TravellerRequestDto.java
  src/main/java/com/deploy/Travalue/travel/domain/Travel.java
  src/main/java/com/deploy/Travalue/travel/domain/TravelContent.java
  src/main/java/com/deploy/Travalue/travel/domain/TravelContentInfoVO.java
  src/main/java/com/deploy/Travalue/travel/domain/TravelInformation.java
  src/main/java/com/deploy/Travalue/travel/domain/TravelPin.java
  src/main/java/com/deploy/Travalue/travel/domain/TravelRoutineInfoVO.java
  src/main/java/com/deploy/Travalue/travel/infrastructure/TravelInformationRepository.java
  src/main/java/com/deploy/Travalue/travel/infrastructure/TravelPinRepository.java
  src/main/java/com/deploy/Travalue/travel/service/TravelService.java
Labels: 🤍 승헌, 🎃 Feat

#59 Fix: contents 배열 pin index로 정렬
  src/main/java/com/deploy/Travalue/travel/controller/TravelController.java
  src/main/java/com/deploy/Travalue/travel/infrastructure/TravelContentRepository.java
  src/main/java/com/deploy/Travalue/travel/infrastructure/TravelRepository.java
  src/main/java/com/deploy/Travalue/travel/service/TravelService.java
Labels: 💚 서현, 🎃 Feat

#60 Feat/#58 travel update
  src/main/java/com/deploy/Travalue/exception/SuccessCode.java
  src/main/java/com/deploy/Travalue/travel/controller/TravelController.java
  src/main/java/com/deploy/Travalue/travel/domain/Travel.java
  src/main/java/com/deploy/Travalue/travel/infrastructure/TravelContentRepository.java
  src/main/java/com/deploy/Travalue/travel/infrastructure/TravelPinRepository.java
  src/main/java/com/deploy/Travalue/travel/service/TravelService.java
Labels: 🤍 승헌, 🎃 Feat
